name: Security Audit
on:
  push:
    paths:
      - Cargo.toml
    branches:
      - master
  pull_request:
    paths:
      - Cargo.toml
  schedule:
    - cron: "0 0 * * *"

jobs:
  cargo:
    name: Cargo
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2.3.0
      - name: Build | Check
        uses: actions-rs/audit-check@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
